### ISSUE TITLE
File link update

### ISSUE THREAD

**Issue by Jiang-Wenming** [UM-CSS/CSSLabs-NLP#1]
The dropbox link https://www.dropbox.com/s/gpjwfq1c652kyyg/profiles.csv.zip?dl=1 (just before section 1.3 reading data) in the file [0_Intro_to_python_text.ipynb](https://github.com/UM-CSS/CSSLabs-NLP/blob/master/0_Intro_to_python_text.ipynb) seems not valid anymore. Could you please update it with a new one?

**Comment by packerliu** [comment]
This has been fixed in current version using a google drive link instead.  Closing it.  The google link might not be accessible when the client is not on the UM network.  That might be an another access issue on the Google Drive.
